name: 'Edit Gist'
inputs:
  gistURL: 
    description: 'URL to the gist'
    required: true
  token:
    description: 'Token able to append to the gist'
    required: true
  file:
    description: 'The filename containing the gist'
    required: true
runs:
  using: 'node12'
  main: 'gist.js'
branding:
  icon: 'align-center'
  color: 'orange'
description: 'Edits a gist'
